spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imobiliaria?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
